version: '0.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - develop
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore src/Jasiri.sln
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build src/Jasiri.sln
after_build:
  # For once the build has completed
artifacts:
clone_depth: 1
test_script:
  # restore packages for our unit tests
  # run the unit tests (requires changing into the test directory)
  - cmd: cd src/Jasiri.Tests
  - cmd: dotnet test
  - cmd: cd ../Jasiri.OpenTracing.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off